// The Themes page's built-in themes: each one's colour roles, light and dark, as mtrl's
// compiled theme CSS declares them (tokens.ts reads it), and its tonal palettes, from the
// seed mtrl generates it from or, for a theme set by hand, from its light primary. The
// seed is read from the header scripts/generate-themes.ts writes in each generated
// theme's SCSS (src/styles is in mtrl's published files); the palettes are the
// engine's (src/shared/theme-engine.ts).
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { root } from './content';
import { themeTokens } from './tokens';
import { themes } from '../shared/button';
import { THEME_ROLES, VARIANTS, themeColors, type ColorSpec, type CoreColor } from '../shared/theme-engine';

export interface BuiltInTheme {
  name: string;
  label: string;
  /** Role → hex for every THEME_ROLES role, from the theme's CSS. */
  roles: { light: Record<string, string>; dark: Record<string, string> };
  /** What mtrl generates the theme from, when it does. */
  origin?: ColorSpec & { text: string };
  /**
   * A hand-made theme's seed for its generated variants: its light primary. Its own
   * colours stay "Original"; its palettes are Tonal Spot's from this seed.
   */
  handSeed?: string;
  palettes: Record<CoreColor, string[]>;
}

/** M3's baseline seed: mtrl's baseline is M3's hand-tuned baseline scheme of this seed (generate-themes.ts, BASELINE_SEED). */
const BASELINE: ColorSpec = { source: '#6750a4', variant: 'tonal-spot', contrast: 0 };
const HEADER = /Generated by scripts\/generate-themes\.ts \(([^)]*)\)/;

/** The spec a generated theme's SCSS header records: `seed #9a7a3e, variant Tonal Spot, secondary #4a87c4`. */
export function originOf(header: string): ColorSpec | undefined {
  const fields = Object.fromEntries(header.split(',').map(part => { const [key, ...value] = part.trim().split(' '); return [key, value.join(' ')]; }));
  const variant = VARIANTS.find(entry => entry.label === fields.variant)?.name;
  if (!/^#[0-9a-f]{6}$/i.test(fields.seed ?? '') || !variant) return undefined;
  return {
    source: fields.seed!.toLowerCase(), variant, contrast: fields.contrastLevel ? Number(fields.contrastLevel) : 0,
    ...(fields.secondary ? { core: { secondary: fields.secondary.toLowerCase() } } : {}),
  };
}

function originFor(name: string): ColorSpec | undefined {
  if (name === 'baseline') return BASELINE;
  const file = resolve(root, 'node_modules/mtrl/src/styles/themes', `_${name}.scss`);
  const header = existsSync(file) ? HEADER.exec(readFileSync(file, 'utf8'))?.[1] : undefined;
  return header ? originOf(header) : undefined;
}

const label = (name: string) => (name.charAt(0).toUpperCase() + name.slice(1)).replaceAll('-', ' ');
const describe = (spec: ColorSpec) => [
  `seed ${spec.source}`, VARIANTS.find(entry => entry.name === spec.variant)!.label,
  ...(spec.core?.secondary ? [`secondary ${spec.core.secondary}`] : []), ...(spec.contrast ? [`contrast ${spec.contrast}`] : []),
].join(', ');

export const builtInThemes: BuiltInTheme[] = themes.map(name => {
  const tokens = themeTokens[name]!;
  const pick = (mode: 'light' | 'dark') => Object.fromEntries(THEME_ROLES.map(role => [role, tokens[mode][role]?.value ?? '']));
  const origin = originFor(name);
  const roles = { light: pick('light'), dark: pick('dark') };
  if (origin) return { name, label: label(name), roles, origin: { ...origin, text: describe(origin) }, palettes: themeColors(origin).palettes };
  const handSeed = roles.light.primary!;
  return { name, label: label(name), roles, handSeed, palettes: themeColors({ source: handSeed, variant: 'tonal-spot', contrast: 0 }).palettes };
});
