// The tonal palettes of the theme: six strips, or, for a theme mtrl sets by hand, a
// line saying why there are none.
import type { App } from '../core/foundation';
import { PALETTES } from '../config/layout';

export const withPalettes = () => (app: App) => {
  const { ui, source } = app;
  return {
    ...app,
    palettes: {
      paint: () => {
        const theme = source.current();
        const known = theme.palettes !== null;
        ui.paletteList.hidden = !known;
        ui.paletteNote.textContent = known
          ? `Generated by mtrl from ${theme.origin}.`
          : `${theme.label}'s colours are set by hand in mtrl, not generated from a seed, so it has no tonal palettes to show.`;
        if (known) for (const [key] of PALETTES) ui[`palette-${key}`].set(theme.palettes![key]);
      },
    },
  };
};
