// The two axes of a scheme, apart from the theme (its seed): the variant and the
// contrast. Each theme opens on its own (a seeded theme's variant at standard contrast,
// a hand-made theme's "Original" colours), served from mtrl's CSS. Any other choice is
// generated by the engine, loaded on first use, from the theme's seed, or, for a
// hand-made theme, from its light primary. `null` in the state means "the theme's own".
import type { App } from '../core/foundation';
import type { ThemeData } from './withThemeSource';
import type { VariantName } from '../../../shared/theme-engine';

export const VARIANTS = [
  ['tonal-spot', 'Tonal Spot'], ['neutral', 'Neutral'], ['vibrant', 'Vibrant'], ['expressive', 'Expressive'], ['fidelity', 'Fidelity'],
  ['content', 'Content'], ['monochrome', 'Monochrome'], ['rainbow', 'Rainbow'], ['fruit-salad', 'Fruit Salad'],
] as const;
export const CONTRASTS = [[0, 'standard', 'Standard contrast'], [0.5, 'medium', 'Medium contrast'], [1, 'high', 'High contrast']] as const;
const label = (variant: string) => VARIANTS.find(([name]) => name === variant)?.[1] ?? 'Original';
const engine = () => import('../../../shared/theme-engine');

export const withVariant = () => (app: App) => {
  const { state, source, roles } = app;
  const seedOf = (theme: ThemeData) => theme.spec?.seed ?? theme.handSeed!;
  const own = (theme: ThemeData) => ({ variant: theme.spec?.variant ?? 'original', contrast: theme.spec?.contrast ?? 0 });
  /** The variant and contrast in effect for the current theme. */
  const effective = () => {
    const theme = source.current();
    return { variant: (state.get('variant') as string | null) ?? own(theme).variant, contrast: (state.get('contrast') as number | null) ?? own(theme).contrast };
  };
  let shown: ThemeData = source.current();
  let request = 0;
  /** The variant and contrast state that produced `shown`. `null` is the theme's own. */
  let applied = { variant: state.get('variant') as string | null, contrast: state.get('contrast') as number | null };
  /** The scheme in effect: the theme as mtrl ships it, a built-in theme that is the same scheme, or the engine's. */
  const derive = async (): Promise<ThemeData> => {
    const theme = source.current();
    const { variant, contrast } = effective();
    const mine = own(theme);
    if (variant === mine.variant && contrast === mine.contrast) return theme;
    // Original on a hand-made theme has standard contrast only: higher ones are Tonal Spot's.
    const generated = variant === 'original' ? 'tonal-spot' : variant;
    const seed = seedOf(theme);
    const secondary = theme.spec?.secondary;
    const same = source.themes.find((t: ThemeData) => t.spec && t.spec.seed === seed && t.spec.variant === generated && t.spec.contrast === contrast && t.spec.secondary === secondary);
    const spec = { seed, variant: generated, contrast, ...(secondary ? { secondary } : {}) };
    const describe = `seed ${seed}, ${label(generated)}${secondary ? `, secondary ${secondary}` : ''}${contrast ? `, contrast ${contrast}` : ''}`;
    if (same) return { ...same, name: theme.name, label: theme.label, seed: theme.seed, handSeed: theme.handSeed, spec, origin: describe };
    const { themeColors } = await engine();
    const colors = themeColors({ source: seed, variant: generated as VariantName, contrast, ...(secondary ? { core: { secondary } } : {}) });
    return {
      ...theme, spec, origin: describe, palettes: colors.palettes,
      light: (roles as string[]).map(role => colors.roles.light[role]!), dark: (roles as string[]).map(role => colors.roles.dark[role]!),
    };
  };
  return {
    ...app,
    variant: {
      own, effective, seedOf,
      shown: () => shown,
      /** Works out the scheme, then calls `done` with it, unless a newer change came first.
       *  A failure calls `failed` and puts the controls back to the scheme in effect. */
      update: (done: (theme: ThemeData) => void, failed?: () => void) => {
        const ticket = ++request;
        const chosen = { variant: state.get('variant') as string | null, contrast: state.get('contrast') as number | null };
        derive().then(theme => {
          if (ticket !== request) return;
          shown = theme;
          applied = chosen;
          done(theme);
        }).catch(() => {
          if (ticket !== request) return;
          // The control already shows the choice; the card is still `shown`.
          state.set('variant', applied.variant);
          state.set('contrast', applied.contrast);
          failed?.();
        });
      },
      /** The address of what is shown: the theme or seed, then any variant and contrast not its own. */
      params: (): URLSearchParams => {
        const theme = source.current();
        const params = new URLSearchParams();
        if (theme.seed) params.set('seed', theme.seed.slice(1));
        else params.set('theme', theme.name);
        const variant = state.get('variant') as string | null;
        const contrast = state.get('contrast') as number | null;
        if (variant !== null && variant !== own(theme).variant) params.set('variant', variant);
        if (contrast !== null && contrast !== own(theme).contrast) params.set('contrast', CONTRASTS.find(([value]) => value === contrast)![1]);
        return params;
      },
      /** A variant or contrast choice: the theme's own is stored as null. */
      setVariant: (variant: string) => state.set('variant', variant === own(source.current()).variant ? null : variant),
      setContrast: (contrast: number) => state.set('contrast', contrast === own(source.current()).contrast ? null : contrast),
    },
  };
};
