// The carousel playground's photos: Lorem Picsum, curated with titles and places for
// vlist.io's carousel demo (vlist.io src/data/carousel.js), twenty-four per layout.
// Lorem Picsum, https://picsum.photos, says "Images from Unsplash" (https://unsplash.com); the service states no licence on https://picsum.photos, read 2026-10-02. The images are loaded from that service at view time, not stored in this repository.
export type CarouselVariant = 'multi-browse' | 'uncontained' | 'hero' | 'hero-center' | 'full-screen';
export interface CarouselPhoto { id: number; title: string; location: string }

const sets: Record<CarouselVariant, [number, string, string][]> = {
  'multi-browse': [
    [68, 'Harbor Pier', 'Australia'],
    [120, 'Milky Way Fence', 'Wyoming'],
    [141, 'Golden Hills', 'California'],
    [191, 'Alpine Pass', 'Swiss Alps'],
    [268, 'Beach Chair', 'North Sea'],
    [403, 'Old Typewriter', 'Antique Shop'],
    [407, 'Sparkler Night', 'Celebration'],
    [427, 'Palm Silhouettes', 'Egypt'],
    [429, 'Fresh Raspberries', 'Kitchen'],
    [475, 'Volcano in Mist', 'Iceland'],
    [585, 'Mountain Stadium', 'Utah'],
    [621, 'Under the Bridge', 'Brisbane'],
    [630, 'Sun Through Pines', 'Dolomites'],
    [685, 'Above the Clouds', 'Summit'],
    [731, 'Cliff Eagle', 'Canary Islands'],
    [766, 'Coffee Beans', 'Roastery'],
    [790, 'Red Deer Stag', 'Richmond Park'],
    [803, 'Tropical Moss', 'Greenhouse'],
    [809, 'Peak in Clouds', 'Huangshan'],
    [832, 'Quiet Reading', 'Vietnam'],
    [885, "Writer's Desk", 'Studio'],
    [945, 'Fire Escapes', 'New York'],
    [1037, 'Half Dome Sunrise', 'Yosemite'],
    [1076, 'Steel Geometry', 'Tokyo'],
  ],
  uncontained: [
    [8, 'Laptop & Coffee', 'Studio'],
    [27, 'Watching Waves', 'California'],
    [34, 'Rusty Barrel', 'Countryside'],
    [36, 'Camera Parts', 'Workshop'],
    [73, 'Baseball Glove', 'Dugout'],
    [76, 'Green Bicycle', 'Vermont'],
    [185, 'Sand Dunes', 'Sahara'],
    [247, 'Red Rock', 'Australia'],
    [296, 'Snow Peaks', 'Rockies'],
    [307, 'Wood Grain', 'Studio'],
    [348, 'Tube Station', 'London'],
    [392, 'Golden Gate', 'San Francisco'],
    [453, 'Stage Light', 'Concert'],
    [588, 'Sunset Jetty', 'Maldives'],
    [757, 'Classic Interior', 'Route 66'],
    [784, 'Morning Dew', 'Meadow'],
    [815, 'Heart Hands', 'Sunset'],
    [869, 'Starry Mountains', 'Norway'],
    [892, 'Rusty Plymouth', 'Junkyard'],
    [926, 'Walking in Fog', 'Highlands'],
    [958, 'Succulents', 'Greenhouse'],
    [1021, 'Misty Canopy', 'Oregon'],
    [1033, 'Escalator', 'Metro'],
    [1073, 'Open Books', 'Library'],
  ],
  hero: [
    [29, 'Himalayan Peaks', 'Nepal'],
    [37, 'Coastal Bluffs', 'Maine'],
    [39, 'Vinyl Groove', 'Studio'],
    [42, 'Morning Coffee', 'Portland'],
    [47, 'Ocean Pier', 'California'],
    [49, 'Santorini Village', 'Greece'],
    [55, 'New Growth', 'Lakeside'],
    [58, 'Stone Lighthouse', 'New England'],
    [59, 'Prairie Fence', 'Midwest'],
    [65, 'Golden Hour', 'Countryside'],
    [67, 'Rolling Hills', 'Carpathians'],
    [69, 'Railway Lines', 'Eastern Europe'],
    [74, 'Bay Crossing', 'San Francisco'],
    [82, 'Cherry Blossoms', 'Spring'],
    [84, 'Bridge at Night', 'New York'],
    [100, 'Hazy Beach', 'Santa Monica'],
    [103, 'Park Afternoon', 'Atlanta'],
    [106, 'Frangipani Blooms', 'Hawaii'],
    [110, 'Pastoral Sunset', 'Netherlands'],
    [119, 'Minimal Desk', 'Studio'],
    [122, 'Millennium Bridge', 'London'],
    [129, 'Golden Gate View', 'San Francisco'],
    [134, 'Fort Point', 'San Francisco'],
    [137, 'Tunnel Light', 'Underground'],
  ],
  'hero-center': [
    [10, 'Island Treeline', 'Pacific Northwest'],
    [51, 'Storm Approaching', 'North Sea'],
    [62, 'Tuscan Sunrise', 'Tuscany'],
    [132, 'Frozen Road', 'Eastern Europe'],
    [271, 'Bosphorus Ferry', 'Istanbul'],
    [278, 'Mountain Tunnel', 'New Zealand'],
    [281, 'Skatepark Kickflip', 'Venice Beach'],
    [314, 'Desert Highway', 'Death Valley'],
    [338, 'Solitude', 'Baltic Sea'],
    [356, 'Lone Surfer', 'Oregon'],
    [412, 'Boreal Lake', 'Quebec'],
    [506, 'Gullfoss Falls', 'Iceland'],
    [544, 'Misty Mountains', 'Appalachia'],
    [629, 'Leaning Tower', 'Pisa'],
    [649, 'Dry Grass', 'California'],
    [670, 'Red Tram', 'Istanbul'],
    [674, 'Harvest Grapes', 'Vineyard'],
    [703, 'City Rainbow', 'New York'],
    [811, 'Forest Canopy', 'Amazon'],
    [876, 'Cloud Forest', 'Black Forest'],
    [882, 'Café Terrace', 'Lisbon'],
    [891, 'Antler Still Life', 'Studio'],
    [912, 'Deep Blue', 'Atlantic'],
    [984, 'Highland Drama', 'Scotland'],
  ],
  'full-screen': [
    [23, 'Silver Forks', 'Kitchen'],
    [31, 'Barefoot', 'Studio'],
    [75, 'Vine Grapes', 'Vineyard'],
    [78, 'Arched Doorway', 'Old Town'],
    [79, 'Summit Hiker', 'Mountains'],
    [156, 'Sand Footprints', 'Beach'],
    [253, 'Mossy Stone', 'Forest Floor'],
    [260, 'Alpine Pines', 'Mountains'],
    [263, 'Winter Street', 'Europe'],
    [486, 'Vintage Typewriter', 'Studio'],
    [508, 'Vaulted Ceiling', 'Cathedral'],
    [512, 'Blue Lagoon', 'Iceland'],
    [514, 'White Land Rover', 'Havana'],
    [520, 'Manhattan Bridge', 'New York'],
    [522, 'Tree-Lined Avenue', 'New York'],
    [530, 'Terrarium', 'Greenhouse'],
    [535, 'Clothing Rack', 'Boutique'],
    [537, 'Shooting Star', 'Night Sky'],
    [550, 'City Sunset', 'Rooftop'],
    [567, 'Bokeh Canopy', 'Garden'],
    [591, 'Cliff in Clouds', 'Mountains'],
    [593, 'Young Tiger', 'Sanctuary'],
    [613, 'Golden Gate', 'San Francisco'],
    [638, 'Coastal Aerial', 'Beach'],
  ],
};

export const carouselPhotos = (variant: CarouselVariant): CarouselPhoto[] => sets[variant].map(([id, title, location]) => ({ id, title, location }));

// About twice the rendered slide: a browse item is up to 280 px wide by default and a hero
// slide about 400 to 700 px, at 3:2; a full-screen slide fills a portrait frame up to
// 400 × 600 px, at 2:3, as vlist.io's portrait set is.
const sizes: Record<CarouselVariant, [number, number]> = { 'multi-browse': [560, 376], uncontained: [560, 376], hero: [800, 536], 'hero-center': [800, 536], 'full-screen': [640, 960] };
export const carouselPhotoUrl = (variant: CarouselVariant, id: number): string => `https://picsum.photos/id/${id}/${sizes[variant][0]}/${sizes[variant][1]}`;
